// BISINDO Bridge — laptop tunnel URL (auto-generated by start-ngrok.sh).
// URL ini berubah setiap kali ngrok restart.
// Untuk testing LAN yang sama: "http://192.168.x.x:5000"
export const LAPTOP_API_URL = "https://elephant-petticoat-trial.ngrok-free.dev";
